In [2]:
import numpy as np

In [4]:
#python listesi
py_list=[1,2,3,4,5,6,7,8,9]

#numpy array
np_array=np.array([1,2,3,4,5,6,7,8,9])

In [5]:
print(type(np_array))

<class 'numpy.ndarray'>


In [6]:
py_multi=[[1,2,3],[4,5,6],[7,8,9]]
np_multi=np_array.reshape(3,3)


In [12]:
print(py_multi)
print(np_multi)

#print(py_multi)
print(np_array.ndim)
print(np_multi.ndim)

print(np_array.shape)
print(np_multi.shape)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
(9,)
(3, 3)
