In [1]:
import numpy as np

In [6]:
numbers = np.array([0,5,10,15,20,25,50,75])

result =numbers[5]
result= numbers[0:3]
result= numbers[:3]
result= numbers[3:]
result= numbers[::]
result= numbers[::-1 ]#tersini yazdırır
print(result)


[75 50 25 20 15 10  5  0]


In [23]:
numbers2 = np.array([[0,5,10],[15,20,25],[50,75,85]])# [15,20,25] satır

result=numbers2[0]
result=numbers2[2]
result=numbers2[0,2]
result=numbers2[2,1]

result=numbers2[:,2] # tüm satırların ikinci indexi [10 25 85], [:] = tüm satırlar
result=numbers2[:,0]
result=numbers2[:,0:2] 
"""[[ 0  5]
    [15 20]
    [50 75]]"""

result=numbers2[-1,:] # [50 75 85]

result=numbers2[:2,:2]
"""
[[ 0  5]
 [15 20]]
"""

print(result)

[[ 0  5]
 [15 20]]


In [27]:
arr1 = np.arange(0,10) # [0 1 2 3 4 5 6 7 8 9]
arr2 = arr1 # referans

print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
