In [2]:
import numpy as np


In [38]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

print(numbers1)
print(numbers2)

result = numbers1+numbers2

result = numbers1+10

result = numbers1-numbers2

result = numbers1-10

result = numbers1 * numbers2

result = numbers1 / numbers2

result =np.sin(numbers1) #sinüs
result =np.cos(numbers1) #kosinüs

result =np.sqrt(numbers1) #karekök

result =np.log(numbers1) #logaritma

result=numbers1>=5 #[ True  True  True  True  True  True]
result=numbers1%2==0

print(numbers1[result]) # dizinin içindeki çift sayıları yazdırır #[22 10 66]

print(result)


[60 72 28 54 30 61]
[64 65 59 55 41 22]
[60 72 28 54 30]
[ True  True  True  True  True False]


In [35]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

mnumbers1=numbers1.reshape(2,3)
mnumbers2=numbers2.reshape(2,3)

print(mnumbers1)
print(mnumbers2)

result= np.vstack((mnumbers1,mnumbers2)) #dikey birleştirme
result= np.hstack((mnumbers1,mnumbers2)) #yatay birleştime

result=numbers1>=5 #[ True  True  True  True  True  True]
result=numbers1%2==0



print(result)

[[94 44 99]
 [32 61 60]]
[[83 80 16]
 [86 93 16]]
[ True  True False  True False  True]
