In [3]:
import numpy as np

In [6]:
#1 den 10 a array oluşturur
result = np.arange(1,10)
result = np.arange(1,100,3)
print(result)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [10]:
#
result = np.zeros(10)
result = np.ones(10)
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [33]:
#sıfırdan 100 e 5 eşit parçaya böler
result = np.linspace(0,100,5)
print(result)

[  0.  25.  50.  75. 100.]


In [47]:
result=np.random.randint(0,10)
result=np.random.randint(10)
result=np.random.randint(1,10,3)

#0 ile 1 arasında 5 sayı üret
result=np.random.rand(5)
print(result)

[0.24741037 0.21510535 0.38484273 0.14618024 0.40991241]


In [52]:
np_array=np.arange(50)
np_multi= np_array.reshape(5,10)
#satırların toplamı
print(np_multi.sum(axis=1))
#sutunların toplamı
print(np_multi.sum(axis=0))

#print(result)

[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]


In [84]:
rnd_numbers=np.random.randint(1,100,10)
#result=rnd_numbers.max()
result=rnd_numbers.min()
#üretilen sayıların ortalaması
result=rnd_numbers.mean()
#print(rnd_numbers)
print(result)

45.6


In [96]:
rnd_numbers=np.random.randint(1,100,10)
#üretilen en büyük sayının indexi
result=rnd_numbers.argmax()
print(rnd_numbers)
print(result)

[55 85 16 84 49 53 17 46 59 28]
1
