In [2]:
import numpy as np


In [21]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

print(numbers1)
print(numbers2)

result = numbers1+numbers2

result = numbers1+10

result = numbers1-numbers2

result = numbers1-10

result = numbers1 * numbers2

result = numbers1 / numbers2

result =np.sin(numbers1) #sinüs
result =np.cos(numbers1) #kosinüs

result =np.sqrt(numbers1) #karekök

result =np.log(numbers1) #logaritma

print(result)


[58 96 77 50 26 30]
[16 38 47 82 59 98]
[4.06044301 4.56434819 4.34380542 3.91202301 3.25809654 3.40119738]


In [28]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

mnumbers1=numbers1.reshape(2,3)
mnumbers2=numbers2.reshape(2,3)

print(mnumbers1)
print(mnumbers2)

result= np.vstack((mnumbers1,mnumbers2)) #dikey birleştirme
result= np.hstack((mnumbers1,mnumbers2)) #yatay birleştime

result=numbers1>=5 #[ True  True  True  True  True  True]

print(result)

[[66 19 38]
 [82 60 86]]
[[10 41 21]
 [57 50 42]]
[ True  True  True  True  True  True]
